language: node_js
os: linux
dist: xenial
node_js:
  - 8.15.0
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - xutils-dev
    - libxi-dev
    - libxxf86vm-dev
    - x11proto-xf86vidmode-dev
    - mesa-utils
    - xvfb
    - libgl1-mesa-dri
    - libglapi-mesa
    - libosmesa6
script:
  - "./generate-pages"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: cache/nebula.gl/website/public
  keep_history: true
  fqdn: nebula.gl
  verbose: true
  on:
    branch: master

